rvm:
  - 1.8.7
  - 2.1.8
  - 2.2.4
  - 2.3.1

gemfile:
  - gemfiles/Gemfile.2.3.capybara1
  - gemfiles/Gemfile.3.2.capybara1
  - gemfiles/Gemfile.3.2.capybara2
  - gemfiles/Gemfile.4.2.capybara2
  - gemfiles/Gemfile.5.0.capybara2

before_script:
  - mysql -e 'create database IF NOT EXISTS spreewald_test;'

script: bundle exec rspec spec

sudo: false

cache: bundler

notifications:
  email:
    - fail@makandra.de

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.2.3.capybara1
      rvm: 2.1.8
    - gemfile: gemfiles/Gemfile.2.3.capybara1
      rvm: 2.2.4
    - gemfile: gemfiles/Gemfile.2.3.capybara1
      rvm: 2.3.1
    - gemfile: gemfiles/Gemfile.3.2.capybara1
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.3.2.capybara2
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.3.2.capybara1
      rvm: 2.3.1
    - gemfile: gemfiles/Gemfile.3.2.capybara2
      rvm: 2.3.1
    - gemfile: gemfiles/Gemfile.4.2.capybara2
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5.0.capybara2
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5.0.capybara2
      rvm: 2.1.8
