# This file is used for Gemika (https://github.com/makandra/gemika) only.
# It will not work with travis-ci.

language: ruby

rvm:
  - 2.1.8

gemfile:
  - tests/rails-3_capybara-1/Gemfile
  - tests/rails-3_capybara-2/Gemfile
