# This file is used for Gemika (https://github.com/makandra/gemika) only.
# It will not work with travis-ci.

language: ruby

rvm:
  - 2.1.8
  - 2.3.7

gemfile:
  - tests/rails-3_capybara-1/Gemfile
  - tests/rails-3_capybara-2/Gemfile
  - tests/rails-4_capybara-3/Gemfile
  - Gemfile.ruby237
  - Gemfile.ruby218

matrix:
  exclude:
    - gemfile: tests/rails-3_capybara-1/Gemfile
      rvm: 2.3.7
    - gemfile: tests/rails-3_capybara-2/Gemfile
      rvm: 2.3.7
    - gemfile: tests/rails-4_capybara-3/Gemfile
      rvm: 2.1.8
    - gemfile: Gemfile.ruby237
      rvm: 2.1.8
    - gemfile: Gemfile.ruby218
      rvm: 2.3.7
